optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 3000
  batch_size: 4096
  save_model: true
  loss: pairwise
  test_step: 3
  reproducible: true
  seed: 2025
  patience: 5

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024

data:
  type: general_cf
  name: amazon

model:
  name: bigcf_agr
  # Basic parameters
  embedding_size: 32
  intent_num: 128
  keep_rate: 0.8
  edge_bias: 0.5
  
  # General hyperparameters
  layer_num: 2
  reg_weight: 1.0e-4
  cl_weight: 1.0e-3
  cl_temperature: 0.1
  kd_weight: 1.0e-2
  kd_temperature: 0.5
  cen_weight: 1.0e-5
  
  # LLM-AGR specific parameters
  prf_weight: 0.1
  mask_ratio: 0.1
  recon_weight: 0.1
  re_temperature: 0.2
  beta: 5.0  # HSIC regularization coefficient
  sigma: 0.25  # Gaussian kernel parameter
  str_weight: 1.0  # Structural knowledge weight
  alpha: 0.1  # LLM knowledge integration weight
  
  # Dataset-specific configurations
  # amazon dataset configuration
  amazon:
    layer_num: 3
    reg_weight: 1.0e-5
    cl_weight: 0.05
    cl_temperature: 0.2
    kd_weight: 1.0e-2
    kd_temperature: 0.2
    cen_weight: 1.0e-5
    # LLM-AGR specific parameters (for amazon dataset)
    prf_weight: 0.15
    mask_ratio: 0.15
    recon_weight: 0.2
    re_temperature: 0.2
    beta: 5.0
    sigma: 0.2
    str_weight: 1.2
    alpha: 0.15
  
  # yelp dataset configuration
  yelp:
    layer_num: 3
    reg_weight: 1.0e-5
    cl_weight: 0.04
    cl_temperature: 0.2
    kd_weight: 1.0e-2
    kd_temperature: 0.2
    cen_weight: 1.0e-5
    # LLM-AGR specific parameters (for yelp dataset)
    prf_weight: 0.12
    mask_ratio: 0.12
    recon_weight: 0.15
    re_temperature: 0.2
    beta: 4.5
    sigma: 0.25
    str_weight: 1.0
    alpha: 0.12
  
  # steam dataset configuration
  steam:
    layer_num: 3
    reg_weight: 1.0e-5
    cl_weight: 0.01
    cl_temperature: 0.2
    kd_weight: 1.0e-2
    kd_temperature: 0.2
    cen_weight: 1.0e-5
    # LLM-AGR specific parameters (for steam dataset)
    prf_weight: 0.08
    mask_ratio: 0.1
    recon_weight: 0.1
    re_temperature: 0.2
    beta: 4.0
    sigma: 0.3
    str_weight: 0.8
    alpha: 0.1
  
  # movie dataset configuration
  movie:
    layer_num: 3
    reg_weight: 1.0e-5
    cl_weight: 0.02
    cl_temperature: 0.2
    kd_weight: 1.0e-2
    kd_temperature: 0.2
    cen_weight: 1.0e-05
    # LLM-AGR specific parameters (for movie dataset)
    prf_weight: 0.1
    mask_ratio: 0.1
    recon_weight: 0.1
    re_temperature: 0.1
    beta: 10
    sigma: 0.25
    str_weight: 1.0
    alpha: 0.1

# Specify collaborative filtering interaction indices for computing graph structure
cf_index:
  enabled: true  # Whether to enable adaptive graph structure learning
  cache_path: './data/processed/cf_index.pkl'  # Cache path