optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 3000
  batch_size: 4096
  save_model: true
  loss: pairwise
  test_step: 3
  reproducible: true
  seed: 2025
  patience: 5

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024

data:
  type: general_cf
  name: amazon
  
model:
  name: lightgcn_agr
  embedding_size: 32
  edge_bias: 0.5
  keep_rate: 0.8
  
  mask_ratio: 0.15
  recon_weight: 0.2
  re_temperature: 0.2
  
  layer_num: 3
  reg_weight: 1.0e-7
  
  prf_weight: 0.02
  
  kd_weight: 1.0e-2
  
  kd_temperature: 0.2
  
  str_weight: 1.0
  
  beta: 5.0
  
  sigma: 0.25
  
  alpha: 0.1
  
  amazon:
    layer_num: 3
    reg_weight: 1.0e-7
    kd_weight: 1.0e-2
    kd_temperature: 0.2
    prf_weight: 0.02
    
    str_weight: 1.2
    
    beta: 3.5
    
    sigma: 0.3
    
    alpha: 0.15
    keep_rate: 0.8
  
  yelp:
    layer_num: 3
    reg_weight: 1.0e-7
    kd_weight: 1.0e-2
    kd_temperature: 0.2
    prf_weight: 0.03
    
    str_weight: 1.5
    
    beta: 4.0
    
    sigma: 0.25
    alpha: 0.2
    keep_rate: 0.8
  
  steam:
    layer_num: 3
    reg_weight: 1.0e-8
    kd_weight: 1.0e-3
    kd_temperature: 0.1
    prf_weight: 0.01
    
    str_weight: 1.0
    
    beta: 2.5
    
    sigma: 0.2
    alpha: 0.08
    keep_rate: 0.8
    
  movie:
    layer_num: 3
    reg_weight: 1.0e-6
    kd_weight: 1.0e-3
    kd_temperature: 0.2
    prf_weight: 0.025
    
    str_weight: 1.3
    
    beta: 4.0
    
    sigma: 0.28
    alpha: 0.18
    keep_rate: 0.8